### ISSUE TITLE
System.TypeException: Cannot call test methods in non-test context

### ISSUE THREAD

**Issue by torynet** [ImJohnMDaniel/advanced-techniques-to-adopt-salesforcedx-unlocked-packages#12]
I think something is a bit off about the TestDataSupplementDIModule code.
I get the following error the first time I access bindings of any kind while that module's binding record exists.
>18:46:47:037 EXCEPTION_THROWN [EXTERNAL]|System.TypeException: Cannot call test methods in non-test context
>18:46:47:037 METHOD_EXIT [263]|01p19000000uaTh|TestDataSupplementDIModule.configure()
>18:46:47:037 METHOD_EXIT [279]|01p19000000uZ3i|di_Binding.Resolver.loadBindings()
>18:46:47:037 METHOD_EXIT [87]|01p19000000uZ3i|di_Binding.Resolver.get()
>18:46:47:037 METHOD_EXIT [60]|01p19000000uZ3n|di_Injector.getInstance(String, Object)
>18:46:47:037 METHOD_EXIT [123]|01p19000000uZ3n|di_Injector.getInstance(System.Type)
>18:46:47:037 METHOD_EXIT [3]|01p19000000uZ4v|Application.ServiceFactory.newInstance(System.Type)
>18:46:47:037 METHOD_EXIT [18]|01p19000000uZ5z|tagr_TagsService.service()
>18:46:47:037 METHOD_EXIT [43]|01p19000000uZ5z|tagr_TagsService.getTagsByRelatedSObject(Set<Id>)
>18:46:47:037 FATAL_ERROR System.TypeException: Cannot call test methods in non-test context
>18:46:46:000 FATAL_ERROR Class.di_Binding.Resolver.loadBindings: line 263, column 1
>18:46:46:000 FATAL_ERROR Class.di_Binding.Resolver.get: line 279, column 1
>18:46:46:000 FATAL_ERROR Class.di_Injector.getInstance: line 87, column 1
>18:46:46:000 FATAL_ERROR Class.di_Injector.getInstance: line 60, column 1
>18:46:46:000 FATAL_ERROR Class.Application.ServiceFactory.newInstance: line 123, column 1
>18:46:46:000 FATAL_ERROR Class.tagr_TagsService.service: line 3, column 1
>18:46:46:000 FATAL_ERROR Class.tagr_TagsService.getTagsByRelatedSObject: line 18, column 1
>18:46:46:000 FATAL_ERROR Class.tagr_FrameController.getRelatedTags: line 43, column 1
>18:46:47:037 FATAL_ERROR System.TypeException: Cannot call test methods in non-test context

I have simply eliminated the TestDataSupplement binding record and the error went away. So, no problem for me really, unless I want to try that functionality out, but I thought you would want to know.

**Comment by ImJohnMDaniel** [comment]
Thanks again @torynet .  This should be fixed now.
